# Generated by Django 4.0.2 on 2022-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Poniedziałek'), ('Tuesday', 'Wtorek'), ('Wednesday', 'Środa'), ('Thursday', 'Czwartek'), ('Friday', 'Piątek'), ('Saturday', 'Sobota'), ('Sunday', 'Niedziela')], max_length=32)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('preparation_time', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
            options={
                'ordering': ['-votes', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RecipePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=36)),
                ('order', models.IntegerField(unique=True)),
                ('day_name', models.ManyToManyField(to='jedzonko.DayName')),
                ('plan', models.ManyToManyField(to='jedzonko.Plan')),
                ('recipe', models.ManyToManyField(to='jedzonko.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='recipes',
            field=models.ManyToManyField(to='jedzonko.Recipe'),
        ),
    ]
