# Generated by Django 2.2.6 on 2022-02-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_preparing'),
        ('jedzonko', '0002_alter_plan_id'),
        ('jedzonko', '0002_auto_20220223_2211'),
    ]

    operations = [
    ]
